// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCc2333ddzBMMaUrHKrlgdZQxrhLkn-6jw',
    appId: '1:1009843765311:web:4fe71d53a3a522d5ab788a',
    messagingSenderId: '1009843765311',
    projectId: 'stronger-kiddos',
    authDomain: 'stronger-kiddos.firebaseapp.com',
    storageBucket: 'stronger-kiddos.firebasestorage.app',
    measurementId: 'G-ZQNVTG1GT2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAStvxkRU12za0B7KJcHER-fLxZ4nKo4zs',
    appId: '1:1009843765311:android:efb3d9a15328c1baab788a',
    messagingSenderId: '1009843765311',
    projectId: 'stronger-kiddos',
    storageBucket: 'stronger-kiddos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTnMQTCoTTnoavkkSlyEl1R23QaQmJoI4',
    appId: '1:1009843765311:ios:e4bcfe3fe00bd8f0ab788a',
    messagingSenderId: '1009843765311',
    projectId: 'stronger-kiddos',
    storageBucket: 'stronger-kiddos.firebasestorage.app',
    iosClientId: '1009843765311-uipl5lb2ud24gepup15dpua88s2t5qg9.apps.googleusercontent.com',
    iosBundleId: 'com.example.strongerkiddos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTnMQTCoTTnoavkkSlyEl1R23QaQmJoI4',
    appId: '1:1009843765311:ios:e4bcfe3fe00bd8f0ab788a',
    messagingSenderId: '1009843765311',
    projectId: 'stronger-kiddos',
    storageBucket: 'stronger-kiddos.firebasestorage.app',
    iosClientId: '1009843765311-uipl5lb2ud24gepup15dpua88s2t5qg9.apps.googleusercontent.com',
    iosBundleId: 'com.example.strongerkiddos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCc2333ddzBMMaUrHKrlgdZQxrhLkn-6jw',
    appId: '1:1009843765311:web:ee0e218299b7c00eab788a',
    messagingSenderId: '1009843765311',
    projectId: 'stronger-kiddos',
    authDomain: 'stronger-kiddos.firebaseapp.com',
    storageBucket: 'stronger-kiddos.firebasestorage.app',
    measurementId: 'G-VEY0P6ZLXF',
  );
}
